swagger: "2.0"
info:
  title: Greeting
  version: "1.0"
tags:
  - name: GreetingService
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /greeting/v1/messages:
    post:
      operationId: GreetingService_SendMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1SendMessageResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1SendMessageRequest'
      tags:
        - GreetingService
definitions:
  v1SendMessageRequest:
    type: object
    properties:
      content:
        type: string
  v1SendMessageResponse:
    type: object
