swagger: "2.0"
info:
  title: Greeting
  version: "1.0"
tags:
  - name: GreetingService
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/greeting/sayhello:
    post:
      operationId: GreetingService_SayHello
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v1HelloResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v1HelloRequest'
      tags:
        - GreetingService
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
  v1HelloRequest:
    type: object
    properties:
      name:
        type: string
  v1HelloResponse:
    type: object
    properties:
      message:
        type: string
