swagger: "2.0"
info:
  title: Greeting
  version: "2.0"
tags:
  - name: GreetingService
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /greeting/v2/messages:
    post:
      operationId: GreetingService_SendMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2SendMessageResponse'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2SendMessageRequest'
      tags:
        - GreetingService
  /greeting/v2/messages/{id}:
    get:
      summary: Get a message.
      operationId: getMessage
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v2GetMessageResponse'
        "400":
          description: BadRequest
          schema:
            $ref: '#/definitions/v2ErrorResponse'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - echo
definitions:
  modelMessage:
    type: object
    properties:
      content:
        type: string
        description: String content of message.
      createdAt:
        type: string
        format: uint64
        description: Unix time when the message was sent.
      id:
        type: string
        description: Id represents the message identifier.
      sender:
        type: string
        description: Who sent the message.
    description: A message model.
    title: Message
    required:
      - id
      - content
      - sender
      - createdAt
  v2ErrorObject:
    type: object
    properties:
      code:
        type: integer
        format: integer
        description: Response code
        title: code
        pattern: ^[0-9]$
      message:
        type: string
        description: Response message
        title: message
        pattern: ^[a-zA-Z0-9]{1, 32}$
  v2ErrorResponse:
    type: object
    properties:
      correlationId:
        type: string
        format: uuid
        example: 2438ac3c-37eb-4902-adef-ed16b4431030
        description: Unique event identifier for server requests
        title: x-correlation-id
        pattern: ^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$
      error:
        $ref: '#/definitions/v2ErrorObject'
    title: ErrorResponse
  v2GetMessageResponse:
    type: object
    properties:
      message:
        $ref: '#/definitions/modelMessage'
    description: A simple message.
    title: GetMessageResponse
    required:
      - message
  v2SendMessageRequest:
    type: object
    properties:
      content:
        type: string
  v2SendMessageResponse:
    type: object
    properties:
      message:
        $ref: '#/definitions/modelMessage'
