swagger: "2.0"
info:
  title: Greeting
  version: "2.0"
tags:
  - name: GreetingService
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /greeting/v2/messages:
    post:
      operationId: GreetingService_SendMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2SendMessageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/v2SendMessageRequest'
      tags:
        - GreetingService
  /greeting/v2/messages/{id}:
    get:
      operationId: GreetingService_GetMessage
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/v2GetMessageResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - GreetingService
definitions:
  modelMessage:
    type: object
    properties:
      content:
        type: string
      createdAt:
        type: string
        format: uint64
      id:
        type: string
      sender:
        type: string
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
      message:
        type: string
  v2GetMessageResponse:
    type: object
    properties:
      message:
        $ref: '#/definitions/modelMessage'
  v2SendMessageRequest:
    type: object
    properties:
      content:
        type: string
  v2SendMessageResponse:
    type: object
    properties:
      message:
        $ref: '#/definitions/modelMessage'
